//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotNet.Tests.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiotNet.Tests.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {
        ///   &quot;botMmEnabled&quot;: true,
        ///   &quot;id&quot;: 103,
        ///   &quot;rankedPlayEnabled&quot;: true,
        ///   &quot;botEnabled&quot;: true,
        ///   &quot;active&quot;: true,
        ///   &quot;freeToPlay&quot;: true
        ///}.
        /// </summary>
        public static string SampleChampion {
            get {
                return ResourceManager.GetString("SampleChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {
        ///   &quot;championPoints&quot;: 61008,
        ///   &quot;playerId&quot;: 34172230,
        ///   &quot;championPointsUntilNextLevel&quot;: 1,
        ///   &quot;championLevel&quot;: 5,
        ///   &quot;championId&quot;: 412,
        ///   &quot;championPointsSinceLastLevel&quot;: 39408,
        ///   &quot;lastPlayTime&quot;: 1457400619000,
        ///   &quot;chestGranted&quot;: true,
        ///   &quot;highestGrade&quot;: &quot;S+&quot;
        ///}.
        /// </summary>
        public static string SampleChampionMastery {
            get {
                return ResourceManager.GetString("SampleChampionMastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {
        ///        &quot;fellowPlayers&quot;: [
        ///          {
        ///              &quot;championId&quot;: 412,
        ///              &quot;teamId&quot;: 200,
        ///              &quot;summonerId&quot;: 29743501
        ///          },
        ///          {
        ///              &quot;championId&quot;: 150,
        ///              &quot;teamId&quot;: 200,
        ///              &quot;summonerId&quot;: 28949950
        ///          },
        ///          {
        ///              &quot;championId&quot;: 76,
        ///              &quot;teamId&quot;: 100,
        ///              &quot;summonerId&quot;: 57421691
        ///          },
        ///          {
        ///              &quot;championId&quot;: 43,
        ///              &quot;teamId&quot;: 100,
        ///              &quot;summ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleGame {
            get {
                return ResourceManager.GetString("SampleGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {
        ///   &quot;queue&quot;: &quot;RANKED_TEAM_5x5&quot;,
        ///   &quot;name&quot;: &quot;Galio&apos;s Brood&quot;,
        ///   &quot;participantId&quot;: &quot;35870943&quot;,
        ///   &quot;entries&quot;: [
        ///      {
        ///         &quot;leaguePoints&quot;: 2,
        ///         &quot;isFreshBlood&quot;: true,
        ///         &quot;isHotStreak&quot;: true,
        ///         &quot;division&quot;: &quot;I&quot;,
        ///         &quot;isInactive&quot;: true,
        ///         &quot;isVeteran&quot;: true,
        ///         &quot;losses&quot;: 11,
        ///         &quot;playerOrTeamName&quot;: &quot;ApeX R Gaming&quot;,
        ///         &quot;playerOrTeamId&quot;: &quot;TEAM-a77c7a20-7f0e-11e4-8c36-c81f66dd45c9&quot;,
        ///         &quot;wins&quot;: 36,
        ///         &quot;miniSeries&quot;: {
        ///           &quot;losses&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleLeague {
            get {
                return ResourceManager.GetString("SampleLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///        {
        ///            &quot;timestamp&quot;: &quot;1234567890000&quot;,
        ///            &quot;eventType&quot;: &quot;PracticeGameCreatedEvent&quot;,
        ///            &quot;summonerId&quot;: &quot;12345678&quot;
        ///        },
        ///        {
        ///            &quot;timestamp&quot;: &quot;1234567890000&quot;,
        ///            &quot;eventType&quot;: &quot;PlayerJoinedGameEvent&quot;,
        ///            &quot;summonerId&quot;: &quot;12345678&quot;
        ///        },
        ///        {
        ///            &quot;timestamp&quot;: &quot;1234567890000&quot;,
        ///            &quot;eventType&quot;: &quot;PlayerSwitchedTeamEvent&quot;,
        ///            &quot;summonerId&quot;: &quot;12345678&quot;
        ///        },
        ///        {
        ///            &quot;timestamp&quot;: &quot;12 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleLobbyEvents {
            get {
                return ResourceManager.GetString("SampleLobbyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {
        ///   &quot;region&quot;: &quot;NA&quot;,
        ///   &quot;matchType&quot;: &quot;MATCHED_GAME&quot;,
        ///   &quot;matchCreation&quot;: 1436660796872,
        ///   &quot;participants&quot;: [
        ///      {
        ///         &quot;masteries&quot;: [
        ///            {
        ///               &quot;rank&quot;: 1,
        ///               &quot;masteryId&quot;: 4111
        ///            },
        ///            {
        ///               &quot;rank&quot;: 4,
        ///               &quot;masteryId&quot;: 4112
        ///            },
        ///            {
        ///               &quot;rank&quot;: 1,
        ///               &quot;masteryId&quot;: 4114
        ///            },
        ///            {
        ///               &quot;rank&quot;: 3,
        ///               &quot;masteryId&quot;: 4122
        ///            },
        ///            {
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleMatch {
            get {
                return ResourceManager.GetString("SampleMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {
        ///         &quot;timestamp&quot;: 1437700807871,
        ///         &quot;champion&quot;: 254,
        ///         &quot;queue&quot;: &quot;RANKED_TEAM_5x5&quot;,
        ///         &quot;season&quot;: &quot;SEASON2015&quot;,
        ///         &quot;matchId&quot;: 1896442090,
        ///         &quot;role&quot;: &quot;NONE&quot;,
        ///         &quot;platformId&quot;: &quot;NA1&quot;,
        ///         &quot;lane&quot;: &quot;JUNGLE&quot;
        ///      }.
        /// </summary>
        public static string SampleMatchReference {
            get {
                return ResourceManager.GetString("SampleMatchReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {
        ///   &quot;matchVersion&quot;: &quot;5.14.0.329&quot;,
        ///   &quot;region&quot;: &quot;NA&quot;,
        ///   &quot;mapId&quot;: 11,
        ///   &quot;season&quot;: &quot;SEASON2015&quot;,
        ///   &quot;queueType&quot;: &quot;RANKED_TEAM_5x5&quot;,
        ///   &quot;matchDuration&quot;: 3091,
        ///   &quot;matchCreation&quot;: 1437696529521,
        ///   &quot;matchType&quot;: &quot;MATCHED_GAME&quot;,
        ///   &quot;matchId&quot;: 1896376478,
        ///   &quot;participants&quot;: [{
        ///      &quot;masteries&quot;: [
        ///         {
        ///            &quot;rank&quot;: 2,
        ///            &quot;masteryId&quot;: 4211
        ///         },
        ///         {
        ///            &quot;rank&quot;: 2,
        ///            &quot;masteryId&quot;: 4213
        ///         },
        ///         {
        ///            &quot;rank&quot;: 1,
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleMatchSummary {
            get {
                return ResourceManager.GetString("SampleMatchSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {
        ///    &quot;frameInterval&quot;: 60000,
        ///    &quot;frames&quot;: [
        ///        {
        ///          &quot;timestamp&quot;: 200,
        ///          &quot;participantFrames&quot;: {
        ///              &quot;3&quot;: {
        ///                &quot;currentGold&quot;: 475,
        ///                &quot;position&quot;: {
        ///                    &quot;y&quot;: 293,
        ///                    &quot;x&quot;: 351
        ///                },
        ///                &quot;minionsKilled&quot;: 2,
        ///                &quot;level&quot;: 1,
        ///                &quot;jungleMinionsKilled&quot;: 2,
        ///                &quot;totalGold&quot;: 475,
        ///                &quot;dominionScore&quot;: 2,
        ///                &quot;participantId&quot;: 3,
        ///                &quot;x [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleMatchTimeline {
            get {
                return ResourceManager.GetString("SampleMatchTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {
        ///   &quot;modifyDate&quot;: 1437703154000,
        ///   &quot;champions&quot;: [
        ///      {
        ///         &quot;id&quot;: 111,
        ///         &quot;stats&quot;: {
        ///            &quot;totalDeathsPerSession&quot;: 64,
        ///            &quot;totalSessionsPlayed&quot;: 12,
        ///            &quot;totalDamageTaken&quot;: 275590,
        ///            &quot;totalQuadraKills&quot;: 2,
        ///            &quot;totalTripleKills&quot;: 2,
        ///            &quot;totalMinionKills&quot;: 783,
        ///            &quot;maxChampionsKilled&quot;: 5,
        ///            &quot;totalDoubleKills&quot;: 1,
        ///            &quot;totalPhysicalDamageDealt&quot;: 162031,
        ///            &quot;totalChampionKills&quot;: 21,
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleRankedStats {
            get {
                return ResourceManager.GetString("SampleRankedStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {
        ///   &quot;region_tag&quot;: &quot;na1&quot;,
        ///   &quot;services&quot;: [
        ///      {
        ///         &quot;incidents&quot;: [{
        ///            &quot;id&quot;: 2740,
        ///            &quot;updates&quot;: [{
        ///               &quot;content&quot;: &quot;Skrill has been disabled while we investigate an issue causing this payment method to fail to grant Riot Points.&quot;,
        ///               &quot;id&quot;: 3182,
        ///               &quot;author&quot;: &quot;test&quot;,
        ///               &quot;updated_at&quot;: &quot;2015-07-19T02:23:43.000Z&quot;,
        ///               &quot;translations&quot;: [
        ///                  {
        ///                     &quot;content&quot;: &quot;Platební metodu Skrill jsme  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleShardStatus {
            get {
                return ResourceManager.GetString("SampleShardStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {
        ///    &quot;from&quot;: [
        ///        &quot;1028&quot;,
        ///        &quot;1052&quot;
        ///    ],
        ///    &quot;description&quot;: &quot;+25 Ability Power
        ///+200 Health
        ///
        ///UNIQUE Passive - Eyes of Pain: +15 Magic Penetration&quot;,
        ///    &quot;gold&quot;: {
        ///        &quot;total&quot;: 1500,
        ///        &quot;sell&quot;: 1050,
        ///        &quot;base&quot;: 665,
        ///        &quot;purchasable&quot;: true
        ///    },
        ///    &quot;tags&quot;: [
        ///        &quot;Health&quot;,
        ///        &quot;MagicPenetration&quot;,
        ///        &quot;SpellDamage&quot;
        ///    ],
        ///    &quot;plaintext&quot;: &quot;Increases magic damage&quot;,
        ///    &quot;into&quot;: [
        ///        &quot;3151&quot;
        ///    ],
        ///    &quot;sanitizedDescription&quot;: &quot;+25 Ability Power +200 Health UNIQUE Pas [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleStaticItem {
            get {
                return ResourceManager.GetString("SampleStaticItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {
        ///   &quot;ranks&quot;: 2,
        ///   &quot;id&quot;: 4211,
        ///   &quot;sanitizedDescription&quot;: [
        ///      &quot;Reduces incoming damage from champion basic attacks by 1&quot;,
        ///      &quot;Reduces incoming damage from champion basic attacks by 2&quot;
        ///   ],
        ///   &quot;description&quot;: [
        ///      &quot;Reduces incoming damage from champion basic attacks by 1&quot;,
        ///      &quot;Reduces incoming damage from champion basic attacks by 2&quot;
        ///   ],
        ///   &quot;name&quot;: &quot;Block&quot;,
        ///   &quot;image&quot;: {
        ///      &quot;w&quot;: 48,
        ///      &quot;full&quot;: &quot;4211.png&quot;,
        ///      &quot;sprite&quot;: &quot;mastery0.png&quot;,
        ///      &quot;group&quot;: &quot;gray_mastery&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleStaticMastery {
            get {
                return ResourceManager.GetString("SampleStaticMastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {
        ///   &quot;playerStatSummaries&quot;: [
        ///      {
        ///         &quot;playerStatSummaryType&quot;: &quot;CoopVsAI&quot;,
        ///         &quot;aggregatedStats&quot;: {
        ///            &quot;averageNodeCaptureAssist&quot;: 2,
        ///            &quot;maxNodeNeutralizeAssist&quot;: 2,
        ///            &quot;totalMinionKills&quot;: 9390,
        ///            &quot;maxChampionsKilled&quot;: 21,
        ///            &quot;totalChampionKills&quot;: 1321,
        ///            &quot;averageChampionsKilled&quot;: 11,
        ///            &quot;averageNumDeaths&quot;: 3,
        ///            &quot;maxNodeCapture&quot;: 11,
        ///            &quot;maxObjectivePlayerScore&quot;: 1174,
        ///            &quot;totalNeutralMi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleStatsSummary {
            get {
                return ResourceManager.GetString("SampleStatsSummary", resourceCulture);
            }
        }
    }
}
